### ISSUE TITLE
createdomain.py cannot add a token authentication domain

### ISSUE THREAD

**Issue by janklaverstijn** [sassoftware/pyviyatools#124]
We have the need to add authentication domains of type token. Currently only password and connection are supported types. Can this be implemented?

 Our local version was updated such that it allows for type=oauth2.0 with the desired result. It's a very simple mod. Just allowing the new type, the REST API will take it from there.

This is the diff that made it work for us in case you'd be interested/willing to incorporate this change in the master:

46c46
< parser.add_argument("-t","--type", help="Type of the domain: password or connection (passwordless).",required=True, choices=['password','connection'])
---
> parser.add_argument("-t","--type", help="Type of the domain: password, oauth2.0 (token) or connection (passwordless).",required=True, choices=['password','connection','oauth2.0'])

**Comment by gerrynelson63** [comment]
@janklaverstijn That seems fairly simple. We can certainly do that. I will try to get to it soon.

**Comment by bruno-mueller-sas** [comment]
Jan, for the sas-viya command there is the credentials plugin that allows to create domains.

Do not know whether it will support what you need, but it is worth a try
sas-viya credentials domains create -h

**Comment by gerrynelson63** [comment]
Bruno is correct, the new credentials plugin was added relatively recently perhaps (finally!) making this tool less necessary.  It looks like it supports "password" and "oauth2.0". Nevertheless, I will still update the tool with your request. That way you can choose the one that best suits your needs.

**Comment by janklaverstijn** [comment]
Thanks for so quickly following up on this! With regards to the CLI approach: we are still on 3.5 so we're missing out on some of the good stuff.
