### ISSUE TITLE
snapshotreport problem when std output is not my screen.

### ISSUE THREAD

**Issue by molestor** [sassoftware/pyviyatools#127]
Hi,
we started using pyviyatools, snapshotreport.py,  a few months ago after an issue with danish special characters was soleved.  Unfortunately it only works if we run snapshotreports 'manually' usige mobaXterm for example.

**_/opt/sas/viya/home/bin/sas-admin transfer download --file /aktivitetsanalyse/va_backup/mol_191-12/_Marketing_Adhoc_Udvidetvejhjælpe-mail_25.json --id c86f5043-ea7e-4232-b8a1-2fe58347f3ec
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/5d2c64d5-26a5-4abe-bcdf-928d0e529e17 --name "8f8498a0-7f71-11ed-8e36-005056a1db28"
running . completed
{
    "items": [
        {
            "contentType": "report",
            "message": "Resource exported successfully",
            "name": "Valideringsrapport_ØS",
            "result": "",
            "state": "completed"
        }
    ]
}

The package with the ID 382c16ec-9214-4383-93c8-dc8d8070fe90 was created._**

If I run the backup through a script in crontab or redirect std output to a file, I get the following error :

{
    "items": [
        {
            "contentType": "report",
            "message": "Resource exported successfully",
            "name": "Bonusopgørelse",
            "result": "",
            "state": "completed"
        }
    ]
}

The package with the ID e39f0e3b-7828-41c3-98eb-351a626e290c was created.

/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/132126c4-fc11-471b-90a5-0621d25511bd --name "353991f2-7c74-11ed-911e-005056a1db28"
/opt/sas/viya/home/bin/sas-admin transfer download --file /aktivitetsanalyse/va_backup/back_2022-12-15_13:30:06/_LedendeMaalinger_Massemarkedet_EndeligeRapporter_BilpartnerSalgstragt_0.json --id cb39a0b5-7bcd-
4ec7-8a77-d54e343724c5
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/3b4e9f4c-f569-4587-9989-e393a05097c1 --name "369fd4de-7c74-11ed-911e-005056a1db28"
Traceback (most recent call last):
  File "/opt/sas/util/pyviyatools/snapshotreports.py", line 180, in <module>
    print(command)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 149: ordinal not in range(128)
  If we schedule using a script in crontab, the script fails

I have taken the output from a manually executed backup, and copied the output from my screen, and compared it with output created using std output to a file.
The output from vimdiff is attached in this issue.
![image](https://user-images.githubusercontent.com/110227057/209635274-eeaa9851-89ad-4a44-8048-b2bf8298de83.png)

We are running pythom [2.7.5]

**Comment by gerrynelson63** [comment]
Let me do some investigation and I will get back to you. I know when I looked at this before, the issue does not occur in Python 3. Is that an option for you?

**Comment by gerrynelson63** [comment]
@molestor I have implemented a fix. Please re-open if it does not fix the problem.

**Comment by molestor** [comment]
@gerrynelson63   thanks a million. I will re-try the snapshop operations asap and let you know.  Happy newyear :-)
