### ISSUE TITLE
Minor update following commit 148

### ISSUE THREAD

**Issue by tomstarr** [sassoftware/pyviyatools#149]
Hi Gerry,

When you have moment, please make these minor tweaks which were remnants of my dev work that I forgot to clear up.

1. Remove the below 3x lines from [applyviyarules.py]

```
## Temporily commented out during script development ##
#
clidir='/opt/sas/viya4'**
```

and uncomment this:
`#clidir=propertylist["sascli.location"]`

2. Remove the below 2x lines from [createcaslibjson.py]

```
## Temporily commented out during script development ##
#clidir='/opt/sas/viya4'
```

Thanks!

**Comment by gerrynelson63** [comment]
Done.
