### ISSUE TITLE
Tree structure export for exportfoldertree.py

### ISSUE THREAD

**Issue by AllanWTham** [sassoftware/pyviyatools#152]
Hi there,

For exportfoldertree.py, is there a way to output in tree structure like Linux tree command?

├── setup.py
├── sharedfunctions.py
├── sharedfunctions.pyc
├── showsetup.py
├── snapshotreports.py
├── submit_jobdef.py
├── submit_jobreq.py
├── SUPPORT.md
├── templates
│   ├── SAS_Email_Message_html.json
│   └── SAS_Email_Message_text.json
├── testfolderaccess.py
├── unittestsadm33.sh
├── unittestsadm34.sh
├── unittestviya4.sh
├── updatedomain.py
├── updatepreferences.py
├── validateviya-manual.md
└── validateviya.py

1 directory, 86 files
-bash-4.2$

**Comment by bruno-mueller-sas** [comment]
You could use this command to do it:
sas-viya folders list-members --path <your SAS folder> --tree --recursive

**Comment by AllanWTham** [comment]
Hi Bruno,

Thanks got it. It works!
