### ISSUE TITLE
Login failed due to an error with the security certificate. The certificate is signed by an unknown authority

### ISSUE THREAD

**Issue by Juan4SAS** [sassoftware/pyviyatools#153]
Hello,

I want to use the pyviyatools but I cannot.

I received above message when login with sas-viya CLI, however I could workaround it with using the -k or --insecure flags.

(I must note, it is not true the Viya site's certificate was signed by an unknown authority, GoDaddy is in fact a recognized CA, but let's leave that aside for now).

I notice that loginviaauthinfo.py has no flag to workaround that message. 

Could you please provide an update that resolves it or provide a workaround for it?

Thank you in advance!
Best regards,
Juan

**Comment by gerrynelson63** [comment]
Hi Juan,

I am sorry you are having problems.

It sounds like you cannot securely login with the sas-viya cli. If you can solve that problem then you will also be able to use the pyviyatool loginviaauthinfo.py.

Some things to check:

Do you have the SSL_CERT_FILE environment variable set? Do you know if it is pointing to the correct certificate file?

Try to do a logon with the --verbose option like this 

`sas-viya --verbose auth login -u youruser -p yourpw`

If you still cannot log on I would recommend contacting Tech Support. 

Please report back how you get on.  We can also start to investigate providing the -k flag with the tools.
Gerry

**Comment by Juan4SAS** [comment]
Hi Gary,

thank you again. It is a pleasure to speak with you, you do know your stuff. It resolved the issue.

This triggered another error, but maybe I will open a different issue id, to keep the subject clear.
