### ISSUE TITLE
Support for other authentication than .authinfo (eg. ./sas-viya auth loginCode)

### ISSUE THREAD

**Issue by Juan4SAS** [sassoftware/pyviyatools#155]
Hello,

I notice the login script support creating a token via standard .authinfo ( and sas-viya auth login). 
However, not all the Viya deployments have a pure LDAP connection. I would say that most work with a Single Sign-On procedure.

In these cases, .authinfo will not help.

Can the script currently support login via Authorization Codes (sas-viya auth loginCode)? And, if not, what is the current workaround to validate systems with SSO?

Thank you in advance!
Best regards,
Juan

**Comment by gerrynelson63** [comment]
In this case, you would have to use sas-viya auth loginCode to authenticate. The tools do not provide a scripted way to do that. 

However, recent changes to the sas-viya CLI and the default setting in Viya mean that you would only have to do the initial authentication every 90 days. You can see the details in this [post](https://communities.sas.com/t5/SAS-Communities-Library/SAS-Viya-CLI-Token-Expiry/ta-p/848183). Please check out the section "SAS Viya CLI Auto-Refresh".
