### ISSUE TITLE
Request for script to disable rules in bulk

### ISSUE THREAD

**Issue by tomstarr** [sassoftware/pyviyatools#162]
As part of the my Auth Model implementation automation project, I have a need to be able to disable OOTB Viya rules en masse, in order for the newly created rules to become effective.

Recently the Viya CLI was enhanced to support the disabling of rules using the command:
'sas-viya authorization disable-rules ...' (and it's antonym 'sas-viya authorization enable-rules ...')
However, both of these commands only support the disabling of a single rule at a time, and they require the rule's ID in order to do this.

Please develop something that will:
1. read in a CSV (sample csv lines at the bottom)
2. run the getruleid.py script to retrieve all of the rules' IDs (e.g. ./getruleid.py -u '+objecturi+' -p '+principal+' -o csv')
3. loop the resulting rule IDs through the Viya CLI's disable-rules command

Thanks heaps!

Sample CSV:
```
"objectUri","principal or principalType"
"/jobExecution/jobRequests/*","authenticatedUsers"
"/jobExecution/jobRequests/*/","authenticatedUsers"
"/jobExecution/jobs/**","authenticatedUsers"
"/jobExecution/jobs/**","authenticatedUsers"
```

**Comment by tomstarr** [comment]
Hi Gerry,
I raised this as an issue after consulting with Ajmal. However, as it happens, I found some time today and was able to write something myself. #163 
![togglerules](https://github.com/sassoftware/pyviyatools/assets/88807168/fdcbc191-844d-4e30-9023-b5e624a20eb3)

Do take a look and see whether it'd tick the boxes for this project, or could do with some refinement.

Thanks.

**Comment by tomstarr** [comment]
Opened a new pull request without the pycache this time :)
[#164](https://github.com/sassoftware/pyviyatools/pull/164)

**Comment by gerrynelson63** [comment]
Thanks for adding this tool Tom, nice work, I have merged it in.
