### ISSUE TITLE
Make the contents for Personal Caslibs visible

### ISSUE THREAD

**Issue by AllanWTham** [sassoftware/pyviyatools#165]
Hi there,

Is it possible for Personal Caslibs to be supported for listcaslibs.py and listcastables.py? Currently, these two utilities do not show contents from Personal Caslibs.

**Comment by gerrynelson63** [comment]
Relevant blog [post](http://sww.sas.com/blogs/wp/gate/33909/viya-administrators-can-now-get-personal-with-users-caslibs/sasgnn/2019/11/12)

**Comment by AllanWTham** [comment]
Yes that is right. But can that be included into  listcaslibs.py and listcastables.py as well?

**Comment by gerrynelson63** [comment]
Sorry Allan, just adding that for documentation as we research if we can do this with the API.

**Comment by AllanWTham** [comment]
All good Gerry! Thanks for your help.

**Comment by gerrynelson63** [comment]
@AllanWTham Unfortunately this one is not possible. There is no way in the CAS Management REST API to become a super user or to run the accessControl.accessPersonalCaslibs action.
