### ISSUE TITLE
Job execution does not return correct returncode

### ISSUE THREAD

**Issue by Bankaifan** [sassoftware/pyviyatools#167]
We are executing jobs using the jobexecution-ID and experiencing the issue, that the sas-admin command always returns returncode 0, even if the job fails.

We have tried setting SYSCC and SYSRC actively to our expected RC, but are still getting 0.

How do we have to exit the SAS-Jobs to get an RC from  the cli that is not 0?

We are using SAS Viya 3.5 and execute the sas-jobs with the command
sas-admin job webapp execute --query-string "_job=/jobDefinitions/definitions/[ID]"

We also tried using the jobs path, but that didn't work.

**Comment by gerrynelson63** [comment]
I don't know the answer to this sorry. Since this is an issue with sas-admin cli you might contact SAS Technical support.
