### ISSUE TITLE
Fix validateviya.py columns

### ISSUE THREAD

**Issue by henriquevaskys** [sassoftware/pyviyatools#175]
Hi

I found out 2 strange outputs from validaiteviya.py

**Test 0: Logged in User**
The columns 'name' and 'id' have their contents swapped. The only way I found to fix it was to change:
 {"id":"0", "name":"Logged in User", "active":"False", "req":['/identities/users/@currentUser'], "cols":['id','name'], 'type':'Data Collection'},
to:
 {"id":"0", "name":"Logged in User", "active":"False", "req":['/identities/users/@currentUser'], "cols":['name', 'id'], 'type':'Data Collection'},

I know it's not the most elegant way of fixing it.

**Test 4: List CAS Server Metrics**
There I found the results for systemNodes and systemCores, and cpuSystemTime and memory are also swapped. I believe it's due the way python reads the data, it must be added and presented in order. Again, the only inelegant was to change the code reflecting the order where /casManagement/servers/<CAS_SERVER>/metrics is presented.

Thanks,
Henri

**Comment by gerrynelson63** [comment]
Thanks Henri for making us aware of that.  I think you are correct about the issue we will do some investigation and fix the problem.

**Comment by gerrynelson63** [comment]
@henriquevaskys , I believe I have fixed the problem. Would you mind testing it? The code is in the branch 175-fix-validateviyapy-columns.

If all goes well I will merge it in.

**Comment by henriquevaskys** [comment]
Hi Gerry, this one looks perfect! Thanks heaps!
btw, I've just noticed "memory" on "Test 4: List CAS Server Metrics" isn't formatted in Mega/Tera notation. Do you think this is an easy fix? 
Cheers,
Henri

**Comment by gerrynelson63** [comment]
You are welcome I will merge the change in.

On the memory, we are just returning what the endpoint provides. It would not be easy in this context to format the value.
