### ISSUE TITLE
no deletion with "python3 archivefiles.py -x" 

### ISSUE THREAD

**Issue by mauriziopinzi** [sassoftware/pyviyatools#191]
Hi,
I have an internal postgres with more than 400k blobs, I need to delete them, these blobs are logs from job execution
With 
_**python3 listfiles.py -n log -p /job -d 35 -o json**_
I'm able to find them but when I run 
**_python3 archivefiles.py -x -n log -d 35 -p /job -fp /tmp_**
I get this message and nothing is deleted
_**The files will be archived. Do you also want to delete the files? (Y)y
NOTE: 0FDD6C53-8249-9042-8C0D-31550BA711CC.log of content type application/vnd.sas.collection+json not supported
NOTE: files archived to the directory /tmp/D20231129T1717S**_

**Comment by gerrynelson63** [comment]
The archive doesn't deal with binary files. I think we could probably delete them without archiving. Would that work for you?

If so I can test an option to delete binary files without archiving.

**Comment by gerrynelson63** [comment]
I fixed a bug in identifying binary files. Also added the option -xx, --deletenoarch   Delete Files without Archiving from Viya
