### ISSUE TITLE
creategroups.py allows a group to be created with no id

### ISSUE THREAD

**Issue by tomstarr** [sassoftware/pyviyatools#192]
Today we accidentally fed the creategroups.py script a CSV file where a group to be created was missing an id attribute. This caused Viya (4 - 2023.09) to create a custom group without an id associated with it.

This in-turn means that the group is visible, yet inaccessible from within EVM and is not delete-able with the Viya CLI.

In reality this issue is caused by the REST API accepting the creation of a custom group with a null "" id attribute. However, whilst I raise that with the devs, could you implement some sort of 'is id value present' check into creategroups.py please?

Thanks,

**Comment by gerrynelson63** [comment]
We can definitely do that.

**Comment by gerrynelson63** [comment]
Fixed
