### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/pyviyatools#20]
How can I find the datasets being used in a report? I am able to get the report uri using listmembers.py but I was wondering if there is a way to connect them both.

**Comment by gerrynelson63** [comment]
We don't have a specific tool that will do that. However, If you have the reportURI you can use the callrestapi tool to get the report elements. One element the DataSource:  

./callrestapi.py -m get -e /reports/reports/3a95ba0d-d2bd-4897-b379-3f7e97a55e83/content/elements

**Comment by veerendra-pappoppula** [comment]
Thank you. I am able to get the datasource element with the above snippet.
