### ISSUE TITLE
urlparse module is missing

### ISSUE THREAD

**Issue by sarveshsood** [sassoftware/pyviyatools#25]
Hi Team,

I tried to run "loginviauthinfo.py" and got below error as "urlparse" is missing. is it a prerequisite?

python loginviauthinfo.py
Traceback (most recent call last):
  File "loginviauthinfo.py", line 46, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by gerrynelson63** [comment]
Yes it is a prerequisite. I will update the README to reflect this.
