### ISSUE TITLE
add support for mapping files in import/export tools

### ISSUE THREAD

**Issue by gerrynelson63** [sassoftware/pyviyatools#29]

**Comment by tomstarr** [comment]
Last week I had real difficulty migrating (importing) content into folders in Viya which were different from where they'd been sourced from.

Found a little workaround for this was to change the folder location in the (previously exported) json file BEFORE trying to import it into Viya (4). Not very pretty, and not particularly elegant, but as a solution it seemed to work.

Perhaps a simple 'find and replace' style tool/function could meet the intent of this Issue?

**Comment by gerrynelson63** [comment]
Hi Tom, the intent of this one was to add support for the Viya mapping files. As you know they do not support remapping the folder on import. I like your idea though :) I will open another issue with that suggestion and maybe we can collaborate on the details.

**Comment by gerrynelson63** [comment]
Import packages now supports --mapping. Added #203 to cover Tom's suggestion
