### ISSUE TITLE
Not an issue: Trying to get email id associated with a user

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/pyviyatools#30]
I tried creating a new file using listgroupsandmembers.py but I am unable to find email id. can you please let me know how to find it?

**Comment by dwstern** [comment]
Hi Verrendra, I wrote this tool so I'll try to help. It's a good question!

The SAS Viya deployment I used to develop this tool connects to an LDAP directory which does have email addresses for users, and those email addresses are retrieved by the SAS Viya Identities services - you can see them in the Users view in SAS Environment Manager just fine. So, they are available to be retrieved somehow.

But, the particular REST endpoint I call in this tool to fetch group members (/identities/groups/'+groupid+'/members') doesn't appear to include the member's email address, if it is a user member, among the fields it returns. Here's a bit of JSON that it does return, for a simple group called Managers with two members, Helena and Sophia:

{u'count': 2, u'name': u'members', u'links': [{u'itemType': u'application/vnd.sas.identity.group.member', u'uri': u'/identities/groups/Managers/members', u'href': u'/identities/groups/Managers/members', u'rel': u'collection', u'type': u'application/vnd.sas.collection', u'method': u'GET'}, {u'itemType': u'application/vnd.sas.identity.group.member', u'uri': u'/identities/groups/Managers/members?depth=1&start=0&limit=50', u'href': u'/identities/groups/Managers/members?depth=1&start=0&limit=50', u'rel': u'self', u'type': u'application/vnd.sas.collection', u'method': u'GET'}], u'items': [{u'name': u'Helena', u'links': [{u'href': u'/identities/users/Helena', u'type': u'application/vnd.sas.identity.user', u'method': u'GET', u'rel': u'self', u'uri': u'/identities/users/Helena'}], u'providerId': u'ldap', u'version': 1, u'type': u'user', u'id': u'Helena'}, {u'name': u'Sophia', u'links': [{u'href': u'/identities/users/Sophia', u'type': u'application/vnd.sas.identity.user', u'method': u'GET', u'rel': u'self', u'uri': u'/identities/users/Sophia'}], u'providerId': u'ldap', u'version': 1, u'type': u'user', u'id': u'Sophia'}], u'accept': u'application/vnd.sas.identity.group.member', u'start': 0, u'version': 2, u'limit': 50}

You just get the user's name, ID and type. No email, or other attributes from that REST endpoint.

However, once you have with the user's ID, you could call another REST endpoint, /users/{userId}, to return a JSON response that does contain the email address (if it was populated in LDAP and retrieved successfully from LDAP by the identities service).

Can you see how to extend this example to do that too?

Best of luck!

David

**Comment by veerendra-pappoppula** [comment]
I exactly did all the steps above before posting the question. I do not know how to view or what the backend contains for me to retrieve and search.

**Comment by dwstern** [comment]
Hi Veerendra, that's good. I've just made an enhancement to listgroupsandmembers.py, so that if you add a -e parameter, it will output user's email addresses if they are present in the LDAP data cached by the identities service. Want to give it a try?

You can see what I changed here: https://github.com/sassoftware/pyviyatools/commit/4aa60e01c4edf8c12b5b02d3ce309e2fa1179f29

This should be a non-breaking change, in that if you do not specify the -e parameter (which did not previously exist), the output should be just as it was before I made this change.

Hope that helps,

David

**Comment by veerendra-pappoppula** [comment]
The output which has 9 values shows the word ldap at the end, which I think is the value being populated for email address as well.

**Comment by dwstern** [comment]
On my test/dev environment, output with 'ldap' as the last value are for one of the following:
1. LDAP groups (as opposed to custom groups) - see the 'membertype' for that row
2. LDAP users who do not have an email address in the directory

If you are seeing 'ldap' in the 'email' column, then something strange is going on. Can you share any example output from your system, anonymised as necessary? (IMPORTANT: please do not share anyone's real email addresses, usernames or user IDs here!)

**Comment by veerendra-pappoppula** [comment]
ex1: SASAdministrators,SAS Administrators,group,local,XXXXXXX,Pappoppula, Veerendra (Ravi),user,ldap
ex2: SAS-IR-STU,SAS-IR-STU,group,ldap,XXX,Dan, Evan ,user,ldap

**Comment by dwstern** [comment]
Hi Veerendra, aah, I think I see what's happening. It looks like some of your LDAP server users have usernames containing a comma:
Pappoppula, Veerendra (Ravi)
Dan, Evan
You (or I) could modify the tool to enclose the username field in quotes, which should fix that.

Also, I don't see a trailing comma or email address on those two example rows of output. Did you run the latest version of listgroupsandmembers.py with the -e parameter on that occasion?

**Comment by veerendra-pappoppula** [comment]
Hi David,

I am new to git and I tried making the changes offline and creating a pull request, but I am unable to. 
the new output to the changes I made looks like this.

SASAdministrators,SAS Administrators,group,local,XXXX,"Pappoppula, Veerendra (Ravi)",user,ldap

I am using the file with -e parameter.

**Comment by dwstern** [comment]
Hi Veerendra,

You obviously figured it out - nice work! I reviewed and accepted your pull request listgroupsandmembers.py (#32). Thank you very much for contributing to this tool!

David

**Comment by dwstern** [comment]
Hi Ravi, okay to close this issue?
David
