### ISSUE TITLE
callrestapi.py --inputfile

### ISSUE THREAD

**Issue by bash-sh** [sassoftware/pyviyatools#34]
Hi,

thanks for this great tool-set.

I'm using `callrestapi.py` downstream for some automation work, but the `--inputfile` parser required for `post` methods only accepts a `string` file path rather than
a) direct JSON payload, or
b) a memory file object (`StringIO`).

It is slightly cumbersome to write-out & read-in just to call the API. Could you please add one of the above options?

Thanks,
Patrick

**Comment by gerrynelson63** [comment]
Patrick,

Glad you are finding the tools useful. I will take a look at this issue and get back to you soon.

Gerry

**Comment by gerrynelson63** [comment]
Closing had a discussion with Patrick and he found a way to access the callrestapi function directly.
