### ISSUE TITLE
getfolderid.py Return Format

### ISSUE THREAD

**Issue by bash-sh** [sassoftware/pyviyatools#35]
Hi Gerry,

could you please add a return option flag to getfolderid.py? At the moment the return format is always:
Id  = 44b4b8b9-7e4a-4f7b-8fbe-330822125652
URI = /folders/folders/44b4b8b9-7e4a-4f7b-8fbe-330822125652
Path = Sub Test 2

Would be great to return this as JSON/CSV for further processing.

Cheers,
Patrick

**Comment by gerrynelson63** [comment]
Patrick, 

Please clone and switch to the branch updateGetTools. Try the version of getfolderid.py in that branch it should.

- behave the same as it does now if you do not use any output options

- support the additional output options of csv and json like many of the other tools

Let me know if that works for you,

Gerry

**Comment by gerrynelson63** [comment]
I have made these changes. You can now optionally return json or csv as well as the current output.
