### ISSUE TITLE
Add prescriptive details to README and INSTALL

### ISSUE THREAD

**Issue by rocoll** [sassoftware/pyviyatools#40]
My pyviyatool - listallcasservercachestatus.py - relies on "tabulate" and "swat" packages. These must be installed by the sysadmin using pip in advance of running, else it fails. My suggestion is to list these kinds of package dependencies as well as the steps to install them in the README and INSTALL pages. Or to go a step further, create a new pyviyatool that can be run to automatically install all package dependencies.

Possibly extend this concept to OS environment variables as well? TLS certs can be vexing for the novice, such as:

```
export SSL_CERT_FILE="/opt/sas/spre/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem"    
# else loginviauthinfo complains "Login failed due to an error with the security certificate. The certificate is signed by an unknown authority"

export REQUESTS_CA_BUNDLE=/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem
# else loginviauthinfo complains "ConnectionError: HTTPSConnectionPool(host='intviya01.race.sas.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))"

export CAS_CLIENT_SSL_CA_LIST=/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/vault-ca.crt
# else swat complains "ERROR: SSL Error: Missing CA trust list"
```

And finally, it's possible that those .crt files do not all exist on the one host where the pyviyatools reside. So that might need to be copied from wherever they have been placed at deployment.

**Comment by gerrynelson63** [comment]
I added the use of a requirement.txt file to cover this issue. Closing.
