### ISSUE TITLE
Export a view of which users have which permissions to which assets in Viya

### ISSUE THREAD

**Issue by vanessaanness** [sassoftware/pyviyatools#52]
We have a requirement, as part of the SAM team, i.e. the SAS team providing the operations of the SAS applications that have been installed for our customers, to be able to provide a view of who has what access to each: folder, report, dataset, model etc in Viya.

This would allow the "product owner" from the customer side to be able to audit the permissions set within Viya if we then made that available to them through VA.

At the moment, I haven't been able to stitch together this view with the current pyviya tools, with my immediate issue being that I can't find a way to convert the UID into the report name, for example.  We have used "listrules" and "explainaccess" to get us some of the way there.

cd /opt/sas/viya/home/bin/; ./sas-admin authorization list-rules | grep "/folders/folders/[0-9]" 
   For each <folder> of the folders output by this script, I’d like to run:
        echo “<folder>” >> access.txt ; ./explainaccess.py -u <folder> >> access.txt

**Comment by gerrynelson63** [comment]
@vanessaanness we will take a look at this request and respond. Thanks.

**Comment by dwstern** [comment]
Hi @vanessaanness, great question. I think there are two ways to approach this. The best is probably based on a script in my 'SAS Viya 3.5: Securing Deployments' workshop in the VLE (https://eduvle.sas.com/course/view.php?id=1802). It has a hands-on exercise which does something that sounds very similar to what you are after. In that workshop's chapter 2 "Users, Groups, Folders and Content" take a look at [hands-on exercise](https://eduvle.sas.com/pluginfile.php/142424/mod_folder/content/0/Hands-On%20Exercises/GELVIYA35SEC_02UsersGroupsFoldersandContent_01.docx?forcedownload=1) 2.3 "List effective permissions on every object under /gelcontent". It uses a script our colleague Ajmal Farzam wrote for the exercise, called "listeffectivepermissions.sh", which takes a folder as an argument. It then lists all the effective permissions on every object it finds recursively below that folder. You may be able to adapt to your purpose without too much extra work, which was why I wanted to include it in an exercise.

Another approach that would do the job, but probably not elegantly enough, would be to use a different script from our SAS Viya 3.5: Administration workshop (https://eduvle.sas.com/course/view.php?id=1748). There, there, coincidentally also in chapter 2 "Initial Administration Tasks", there is coincidentally also [hands-on exercise](https://eduvle.sas.com/pluginfile.php/138863/mod_folder/content/0/Hands-On%20Exercises/GELVIYA35ADM_02InitialTasks_01.docx?forcedownload=1) 2.3 "Test permissions to validate that your folders are correctly secured", which uses a pyviyatool called "testfolderaccess.py". That one only tests folder permissions, so it would rely on you assuming that everything inside a folder was secured in the same way as the folder - this is NOT a safe assumption of course. But it works by ASSERTING that a given user or group does or does not have a given permission on a given folder. You would compile a large array of such assertions, and run the script to have it call out exceptions to your tests (crudely put it yells "Oi, this folder here isn't accessible/inaccessible to user X as you said it was - go take a look"). The solution script for that exercise, /root/admin/solutions/initialtasks/02_securefolders/securefolders_handson1_3.sh, is a small example, and it has a couple of tests in it that fail on purpose so you can see how that looks:

```
[root@intviya01 02_securefolders]# ./securefolders_handson1_3.sh
Logging in with profile:  Default
Getting Credentials for: sasviya01.race.sas.com
Enter credentials for http://sasviya01.race.sas.com:
Login succeeded. Token saved.
The next two tests are expected to fail - we have included them in the test script to show what that looks like.
Exception: TEST FAILED: the effective update permission for HR on folder /gelcontent/GELCorp/HR/Analyses is prohibit, not grant
Exception: TEST FAILED: the effective delete permission for HR on folder /gelcontent/GELCorp/HR/Analyses is prohibit, not grant
That is the end of the two tests which are supposed to fail.
[root@intviya01 02_securefolders]#
```

**Comment by vanessaanness** [comment]
Thank you so much for getting back to me so quickly on this @dwstern   Let me try your first suggestion and then get back to you on how it went and pass on any modifications we make to you in case it can be of use elsewhere.

**Comment by vanessaanness** [comment]
hi @dwstern , I had a thought last night... is there anything in Viya that exposes any row-level permissions that have been granted to a dataset?

**Comment by dwstern** [comment]
Hi Vanessa, there certainly is. You can see what row-level permissions have been granted to a dataset (or we might say, which of the access controls applied to a CAS table include a filter on a grant of the select permission) in lots of different ways.

It's shown in the web UI in the authorizations dialog using a half-filled green circle (search for the term "Row Level" in https://go.documentation.sas.com/?docsetId=calauthzcas&docsetTarget=n10ey3zz0qwxrsn0z6l25qo310q7.htm&docsetVersion=3.5&locale=en#p16uhhe07hc3j8n168b9h5qf5lb7 to see an example).

If you run a sas-admin CLI command like this: 
./sas-admin cas tables list-controls --server cas-shared-default --caslib hrdl --table HR_SUMMARY

You any row level filters applied to the table are reported as having a "tableFilter" in the JSON results. Here's an example showing just three access control applied to a table, of which two are a row-level grants (the ones with "tableFilter" in their attributes):
```
{
    "accept": "",
    "count": 1,
    "details": null,
    "errorCode": 0,
    "httpStatusCode": 0,
    "items": [
        {
            "createdBy": "geladm",
            "creationTimeStamp": "2020-06-05T02:34:38.461Z",
            "identity": "HR",
            "identityType": "group",
            "origin": "direct",
            "permission": "select",
            "tableFilter": "upcase(department) in ('SUB::SAS.IdentityGroups')",
            "type": "grant",
            "version": 1
        },
        {
            "createdBy": "geladm",
            "creationTimeStamp": "2020-06-05T02:34:41.249Z",
            "identity": "Sales",
            "identityType": "group",
            "origin": "direct",
            "permission": "select",
            "tableFilter": "department = 'sales'",
            "type": "grant",
            "version": 1
        },
        {
            "createdBy": "geladm",
            "creationTimeStamp": "2020-06-05T02:34:41.249Z",
            "identity": "Sales",
            "identityType": "group",
            "origin": "direct",
            "permission": "limitedPromote",
            "type": "grant",
            "version": 1
        }
    ],
    "limit": 0,
    "message": "",
    "name": "accessControls",
    "start": 0,
    "version": 2
}
```

There are loads more ways to see this - you can get it in CASL, python etc. too.

Some of this is covered (more setting row-level filters than reporting on them) in the two workshops I mentioned before, in the respective chapters on CAS data. If you search either workshop's CAS data hands-on exercises for "row-level" you'll see several examples.

Hope that helps!

David

**Comment by vanessaanness** [comment]
Hi @dwstern , it certainly does!   We will add the row-level permissions to our holistic view of content vs people who have what access to it and feed back to you the script we create for this.  Many thanks!

**Comment by dwstern** [comment]
Closing as resolved after long period of inactivity.
