### ISSUE TITLE
Do we have any system health check REST API which support Viya 3.5?

### ISSUE THREAD

**Issue by venkattoluchuri** [sassoftware/pyviyatools#53]

**Comment by gerrynelson63** [comment]
Pyviyatools does not have any health check functionality. We try to be a companion to the sas-admin cli and not reproduce functionality that already exists. The sas-admin cli has a healthcheck plugin that should be what you are looking for:

/opt/sas/viya/home/bin/sas-admin healthcheck
NAME:
   sas-healthcheck

USAGE:
   sas-admin healthcheck command [command options] [arguments...]

COMMANDS:
   help, h              Shows a list of commands or help for one command.
   machines             Displays information and settings for the machines in this deployment.
   services             Displays information and settings for the services in this deployment.
   system-health        Displays health information for the services and applications in this deployment.

**Comment by gerrynelson63** [comment]
I hope I answered your question. Please re-open if I did not.
