### ISSUE TITLE
listcastablesandeffectiveaccess.py Enhancement Request

### ISSUE THREAD

**Issue by suktim** [sassoftware/pyviyatools#59]
We have been using some of the pyviyatool scripts and are seeking an enhancement to this script.

Within the permission columns of this script output, it only returns a few sets of permission descriptions (grantInherited, grantDirect, and denyInherited).

Enhancement Request
•	Identify that it is row-level security as a description
•	Display the content of the row-level security in a column 
 
All the custom groups above highlighted in yellow do have row-level security applied to them, but we are unable to tell through the current descriptions.  
![RLS](https://user-images.githubusercontent.com/65611292/90484426-10833180-e12e-11ea-9db6-b0e39f700b4f.jpg)

**Comment by dwstern** [comment]
Hi Abiola,

Please take a look at my first pass at meeting this enhancement request: an updated version of listcastablesandeffectiveaccess.py in a branch named ds_listcaslibsandeffectiveaccess.

See: [https://github.com/sassoftware/pyviyatools/blob/ds_listcaslibsandeffectiveaccess/listcastablesandeffectiveaccess.py](https://github.com/sassoftware/pyviyatools/blob/ds_listcaslibsandeffectiveaccess/listcastablesandeffectiveaccess.py).

Use the new parameters --rowlevelsecurity and optionally --sourcetables to get the tool to report when there are filters on the select permission for a principal, and what the filter expression is.

Would you try it out and let me know how you get on?

**Comment by dwstern** [comment]
Closing as candidate solution was merged and no further feedback received.
