### ISSUE TITLE
Error received when running snapshotreports.py script

### ISSUE THREAD

**Issue by sukprp** [sassoftware/pyviyatools#65]
Hello, I do the platform administration at DIO through the SAS SAM team. 
The sas developers have implemented the snapshotreports.py script to take the report backups from certain content folders.  This script has been running fine on a daily basis until recently.

The script that is scheduled to run is as below :- 
#!/bin/bash

#login#
. /root/.login
sleep 2
cd /opt/pyviyatool/pyscripts/
./loginviauthinfo.py -f ~/.authinfo
######################################
#take report backup#
cd /opt/pyviyatool/pyscripts/
./snapshotreports.py -f /"Admin" -d /sasbackup/reportbackup/Admin_Backup/RS"$(date +"%Y%m%d_%H%M")" -q -c 365
./snapshotreports.py -f /"1. BI Team Development" -d /sasbackup/reportbackup/BI_Backup/RS"$(date +"%Y%m%d_%H%M")" -q -c 365
./snapshotreports.py -f /"2. Analytics Development" -d /sasbackup/reportbackup/Analytics_Backup/RS"$(date +"%Y%m%d_%H%M")" -q -c 365
./snapshotreports.py -f /"3. Production Content" -d /sasbackup/reportbackup/Production_Content_Backup/RS"$(date +"%Y%m%d_%H%M")" -q -c 365
./snapshotreports.py -f /"UAT Content" -d /sasbackup/reportbackup/UAT_Content_Backup/RS"$(date +"%Y%m%d_%H%M")" -q -c 365

Error when we ran the snapshotscript.sh script  ~14:40 on 20th Jan2021

[root@ffffffffff scripts]# ./snapshotscript.sh
Logging in with profile:  Default
Getting Credentials for: sas-portal.ddd.ddd.ddd.dd
Enter credentials for https://sas-portal.ddd.ddd.ddd.dd:
Login succeeded. Token saved.
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/51655a69-1b46-4d20-9a05-f17e0e5ed336 --name "036dd606-5b2e-11eb-9827-00505695a4c2"
The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: c1075b90cf252812
        path: /transfer/exportJobs
{"errorCode":0,"details":["traceId: 527d2f7f2f8bebc0","path: /transfer/packages"],"links":[],"version":2,"httpStatusCode":500}
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/2b6d624a-e6ca-43ae-b5ae-1131284a1ab5 --name "0ba8459a-5b2e-11eb-80fa-00505695a4c2"
The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: d71f9a02e3727324
        path: /transfer/exportJobs
{"errorCode":0,"details":["traceId: 58fd8329b8840054","path: /transfer/packages"],"links":[],"version":2,"httpStatusCode":500}
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/ac661f37-3b74-425c-8bdf-bca78f21bad7 --name "14c69dfc-5b2e-11eb-a882-00505695a4c2"
The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: c5c8214726fababa
        path: /transfer/exportJobs
{"errorCode":0,"details":["traceId: 7f3e98256f39fd65","path: /transfer/packages"],"links":[],"version":2,"httpStatusCode":500}
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/c63715b5-14bd-42dc-b6b3-923277998734 --name "20ac9b44-5b2e-11eb-9067-00505695a4c2"
The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: 7e680f17c74eda38
        path: /transfer/exportJobs
{"errorCode":0,"details":["traceId: ab32f6533fb434c4","path: /transfer/packages"],"links":[],"version":2,"httpStatusCode":500}
/opt/sas/viya/home/bin/sas-admin transfer export -u /reports/reports/582c4bbf-d00d-4a9d-a37a-3275c5e46cc6 --name "2905b4e2-5b2e-11eb-97c3-00505695a4c2"
The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: dfaaa1ecc3c4b608
        path: /transfer/exportJobs
{"errorCode":0,"details":["traceId: aa7b088094889b08","path: /transfer/packages"],"links":[],"version":2,"httpStatusCode":500}

It was observed that the folder timestamp was updated after the script was run.

inside /sasbackup/reportbackup/

drwxr-xr-x. 9 root root 167 Jan 20 14:41 Admin_Backup
drwxr-xr-x. 9 root root 167 Jan 20 14:44 Analytics_Backup
drwxr-xr-x. 9 root root 167 Jan 20 14:44 BI_Backup
drwxr-xr-x. 9 root root 167 Jan 20 14:45 Production_Content_Backup
drwxr-xr-x. 9 root root 167 Jan 20 14:45 UAT_Content_Backup

What was observed was that the folder structure gets updated and new folder is created for the backups to happen - but these folders are empty
inside /sasbackup/reportbackup/Admin_Backup

drwxr-xr-x. 2 root root 6 Jan 14 21:00 RS20210114_2100
drwxr-xr-x. 2 root root 6 Jan 15 21:00 RS20210115_2100
drwxr-xr-x. 2 root root 6 Jan 16 21:00 RS20210116_2100
drwxr-xr-x. 2 root root 6 Jan 17 21:00 RS20210117_2100
drwxr-xr-x. 2 root root 6 Jan 18 21:00 RS20210118_2100
drwxr-xr-x. 2 root root 6 Jan 19 21:00 RS20210119_2100
_**drwxr-xr-x. 2 root root 6 Jan 20 14:41 RS20210120_1441**_

output of du -h /sasbackup/reportbackup/Admin_Backup

0       /sasbackup/reportbackup/Admin_Backup/RS20210114_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210115_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210116_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210117_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210118_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210119_2100
0       /sasbackup/reportbackup/Admin_Backup/RS20210120_1441
0       /sasbackup/reportbackup/Admin_Backup

Please advise on what is going wrong in the script and how we can fix the script so that we can have report backups happening.

**Comment by gerrynelson63** [comment]
I will see if I can reproduce the error.  The error seems to be coming from the transfer cli. Would you mind trying an export outside of the tool with the --verbose option added and send the console output . For example:

`/opt/sas/viya/home/bin/sas-admin --verbose transfer export -u /reports/reports/51655a69-1b46-4d20-9a05-f17e0e5ed336 --name "036dd606-5b2e-11eb-9827-00505695a4c2" `

**Comment by sukprp** [comment]
Hello,

Below is the output when I ran the above mentioned command.

Thanks,
Pradnya.

[root@FFFFFFFF pyscripts]# /opt/sas/viya/home/bin/sas-admin --verbose transfer export -u /reports/reports/7a438285-55dc-4767-9088-264ec80622ea --name "036dd606-5b2e-11eb-9827-00505695a4c2"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language=[]
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en\"}"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[zh-Hans zh-SG zh-HK zh-MO zh-Hant en ja ko zh-CN zh-TW]"
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[zh-Hans zh-Hant zh-CN zh-TW zh-MO en ja ko zh-SG zh-HK]"
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en-GB.properties" err="open GoMessages_en-GB.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en-GB.properties" err="open GoMessages_en-GB.properties: file does not exist"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[zh-Hant ja zh-SG zh-TW zh-HK zh-MO zh-Hans en ko zh-CN]"
level=debug msg="Adding translation func for locale" language=en_GB.UTF-8
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en_GB.UTF-8\"}"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language=[]
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en\"}"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[ja zh-CN en zh-Hans zh-Hant zh-SG zh-TW zh-HK zh-MO ko]"
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en-GB.properties" err="open GoMessages_en-GB.properties: file does not exist"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[zh-MO zh-CN en ja ko zh-HK zh-SG zh-Hans zh-Hant zh-TW]"
level=debug msg="Adding translation func for locale" language=en-GB
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en-GB\"}"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en.properties" err="open GoMessages_en.properties: file does not exist"
level=debug msg="Unable to access bundle, GoMessages_en-GB.properties" err="open GoMessages_en-GB.properties: file does not exist"
level=debug msg="Added translations for locales" language=[]
level=debug msg="Added translations for locales" language="[zh-TW zh-Hans zh-Hant en ja ko zh-CN zh-SG zh-HK zh-MO]"
level=debug msg="Adding translation func for locale" language=en_GB.UTF-8
level=debug msg="Adding translation func for language" language=en
level=debug msg="Error finding translation function" err="no supported languages found []string{\"en_GB.UTF-8\"}"

POST /transfer/exportJobs HTTP/1.1
Host: sas-portal.dd.dd.dd.dd
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Accept: application/vnd.sas.transfer.export.job+json
Accept-Language: en-GB,en
Accept-Locale: en-GB,en
Authorization: <AUTHORIZATION>
Content-Type: application/vnd.sas.transfer.export.request+json
Accept-Encoding: gzip

9d
{"version":0,"name":"036dd606-5b2e-11eb-9827-00505695a4c2","description":"","items":["/reports/reports/7a438285-55dc-4767-9088-264ec80622ea"],"options":null}
0



HTTP/1.1 500
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' *.sas.com blob: data:; style-src 'self' 'unsafe-inline'; child-src 'self' blob: data: mailto:;
Content-Type: application/vnd.sas.error+json; version=2;charset=UTF-8
Date: Fri, 22 Jan 2021 14:50:50 GMT
Expires: 0
Pragma: no-cache
Sas-Service-Response-Flag: true
Server: Apache/2.4
Set-Cookie: dtCookie=v_4_srv_1_sn_7142B1B6AF350349D06B54AFA45DFFFE_perc_100000_ol_0_mul_1; Path=/; **Domain=.dd.uk**
Strict-Transport-Security: max-age=31536000
Vary: User-Agent
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Oneagent-Js-Injection: true
X-Xss-Protection: 1; mode=block

80
{"errorCode":0,"details":["traceId: 4b07120c75754097","path: /transfer/exportJobs"],"links":[],"version":2,"httpStatusCode":500}
0


The following errors have occurred:

1 error occurred:
  * The server failed to fulfill an apparently valid request.
Http Status: 500
Detailed Messages:
        traceId: 4b07120c75754097
        path: /transfer/exportJobs
[root@FFFFFFFF pyscripts]#

**Comment by gerrynelson63** [comment]
It looks like you are not able to do an export outside of the tool. Can you confirm that is the case. Do you get the same error if you try to export a report or folder using the sas-admin cli?

**Comment by sukprp** [comment]
> It looks like you are not able to do an export outside of the tool. Can you confirm that is the case. Do you get the same error if you try to export a report or folder using the sas-admin cli?

We had an issue when Snapshot backups were taken and the Report backup started falling over.  Recently we did a complete shutdown and restart of the services and seems to have fixed the issue and the reportbackups have started working now. It seems that for a short period of time we were unable to export/copy reports. But now we can and this track can be closed. Thanks.

**Comment by gerrynelson63** [comment]
Glad you are back in business. Thanks for the update.
