### ISSUE TITLE
applyfolderauthorization.py comments on csv file are misleading

### ISSUE THREAD

**Issue by pavel-analytium** [sassoftware/pyviyatools#76]
An instruction on what the csv file must contain for using it with the applyfolderauthorization.py says: 
“# Format of input csv file is 6 columns
# Column 1 is the full path to the folder
# Column 2 is the principal type
# Column 3 is the principal name
# Column 4 is the access setting (grant or prohibit)
# Column 5 is the permissions on the folder
# Column 6 is the conveyed permissions on the folder's contents” (https://github.com/sassoftware/pyviyatools/blob/master/applyfolderauthorization.py).
But actually Column 3 should contain the principal id (not name!) otherwise (if principal name is not equal principal id) the applied rule will not be effective and there will be an alert that principal is not found.
Haven't checked, but the same issue may be found in other scripts.

**Comment by gerrynelson63** [comment]
Issue is fixed.
