### ISSUE TITLE
Warning notice request for setup.py

### ISSUE THREAD

**Issue by tomstarr** [sassoftware/pyviyatools#89]
Trivial request to add a big **bold** note (or similar) in the the INSTALL.md and setup.py files (or a prompt to have the user confirm that their system is using Viya 4) to reinforce the fact that setup.py **should not be run if these scripts are being used with Viya 3**, _if_ setup.py is used, then the scripts will no longer function.

I fully appreciate that this could be classed as an ID10T issue, but the more idiot-proof these scripts are the better. :)

**Comment by gerrynelson63** [comment]
@tomstarr done.

Added this note:

**NOTE. You do not need to run setup.py if you are using Viya 3.x and the tools are installed in the default location.**
